"""empty message

Revision ID: 190658eafe0a
Revises: 03f52fa9b4b0
Create Date: 2024-08-16 11:50:21.054098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190658eafe0a'
down_revision = '03f52fa9b4b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accolades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))
        batch_op.drop_column('accolade_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accolades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accolade_type', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
