"""adding image column.

Revision ID: 61c8be7354aa
Revises: f9fe0d515d4a
Create Date: 2024-08-12 15:08:03.615202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c8be7354aa'
down_revision = 'f9fe0d515d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('courses', schema=None) as batch_op:
       # batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('courses', schema=None) as batch_op:
        #batch_op.drop_column('image_url')
    pass
    # ### end Alembic commands ###
